<?php
/**
 * @file
 * Code for the UL meeting content type feature.
 */

function mcommunity_field_validator_form_alter(&$form, &$form_state, $form_id) {
	//web platform services /request form=webform_client_form_10, tho
	if ($form_id == 'webform_client_form_10') {
		//echo "<pre>";var_dump($form["submitted"]["shortcode"]);echo "</pre>";
		$form["submitted"]["mcommunity_group"]["#element_validate"][] = 'mcommunity_field_validator_form_webform_client_form_10_alter';
  	}   
}


/**
 * FAPI validation of an individual number element.
 */
function mcommunity_field_validator_form_webform_client_form_10_alter($element, &$form_state) {
	
	if (isset($element['#value'])) {
		$dator = $element['#value'];
		if (strpos($dator, '@umich.edu') !== false) {
    		//remove @umich.edu and reassign
			$dator = str_replace("@umich.edu","",$dator);
		}
		//check in LDAP if group exists
		$ldaphost = "ldaps://ldap.umich.edu"; 
		$ldapport = 636;
		$ldapconn = ldap_connect($ldaphost, $ldapport);
		  
		if ($ldapconn) {		
			$ldapbind = ldap_bind($ldapconn);
			if ($ldapbind) {
				$dn = "ou=User Groups,ou=Groups,dc=umich,dc=edu";
				$query = "(umichGroupEmail=$dator)";
				$result = ldap_search($ldapconn, $dn, $query);
				$ldapcount = ldap_count_entries($ldapconn,$result);
				if (isset($ldapcount) && $ldapcount > 0) {
					$info = ldap_get_entries($ldapconn, $result);
					//http://documentation.its.umich.edu/node/374
					if (isset($info[0]["membersonly"][0])) {
						if ($info[0]["membersonly"][0] == "TRUE") {
							$message = t('MCommunity group %field is Private, please choose a group we can email, or <a href="http://documentation.its.umich.edu/node/356#Settings">make your group able to receive messages from non-members</a>.', array('%field' => $dator));
							form_error($element, $message);							
						}
					}
				}
				else {
					$message = t('Invalid MCommunity group: %field', array('%field' => $dator));
					form_error($element, $message);
				}			
			}
		}
	}
}